name: Sumo Logic Collector
version: 1.0.0
slug: sumologic_collector
description: An addon to send logs to Sumo Logic
init: false
arch:
  - amd64
startup: application
boot: auto
options:
  access_id: ""
  access_key: ""
  collector_name: HomeAssistantCollector
schema:
  access_id: str
  access_key: str
  collector_name: str
map:
  - config:ro